### ISSUE TITLE
Got error "Too much level of symbolic links"

### ISSUE THREAD

**Issue by evilcel3ri** [akihikodaki/cld3-ruby#12]
Hello !

I'm trying to run the `bundle install` for mastodon which requires cld3, however, I run in to this issue : 
```
feature_extractor.h:45:47: fatal error: cld_3/protos/feature_extractor.pb.h: Trop de niveaux de liens symboliques
 #include "cld_3/protos/feature_extractor.pb.h"

```
I'm on debian 9 amd64 and run ruby 2.4.1. 

Thanks !

**Comment by akihikodaki** [comment]
Thank you for reporting the issue. I would like to know:
* whether you are following [Mastodon Production Guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md) (It helps to understand what you are actually doing if so.)
* whether your bundle path includes symbolic links (e.g. installing to vendor/bundle where vendor is a symbolic link)
* whether your file system supports symbolic links (try to make a symbolic link in the same file system for diagnosis.)

**Comment by evilcel3ri** [comment]
Hello ! Thanks for your quick answer :)

> whether you are following Mastodon Production Guide (It helps to understand what you are actually doing if so.)

I was following this : [the development guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md)

> whether your bundle path includes symbolic links (e.g. installing to vendor/bundle where vendor is a symbolic link)

I'm fairly new to this, so I'm not sure to understand. I have the default settings everywhere and haven't change anything.

> whether your file system supports symbolic links (try to make a symbolic link in the same file system for diagnosis.)

Yes it does :)

**Comment by akihikodaki** [comment]
Do you use rbenv or rvm? If so, please refer to its documentation for the path of gems. Otherwise, your gems should be located at `$HOME/.gem/ruby` (e.g. `/home/aki/.gem/ruby` for me) See if `/home`, `/home/aki`, `/home/aki/.gem` and `/home/aki/.gem/ruby` are symbolic links or not in the example.

**Comment by evilcel3ri** [comment]
Ok, I've cleaned up my ruby settings and gems and upgrade to more recent ruby. This issue disappeared. Sorry for the trouble. Have a nice day and thank you !

**Comment by DeeUnderscore** [comment]
For reference to anyone else who might be in this position: I just encountered the same problem, and the cause was improperly installed/missing protobuf compiler.
