### ISSUE TITLE
JRuby? FFI?

### ISSUE THREAD

**Issue by headius** [akihikodaki/cld3-ruby#13]
Hello! I just ran into your library while trying to set up Mastodon on JRuby. The extension does not look very big. It would be great if cld3-ruby could work on JRuby!

I was wondering why this library is not simply using FFI? Is it because of C++?

I would like to help get an FFI version (or a JRuby version through some other means) of cld3-ruby!

**Comment by akihikodaki** [comment]
cld3-ruby uses FFI.

**Comment by akihikodaki** [comment]
I have identified a problem in JRuby and found a fix. Apply this:
https://github.com/jruby/jruby/pull/4118
