### ISSUE TITLE
Failed to locate Protobuf on Windows.

### ISSUE THREAD

**Issue by FranConcaro** [akihikodaki/cld3-ruby#25]
Hi, I'm having this issue, while trying to install  `cld3`. I've read all the issues before. But none of them had the fix I need.
![image](https://user-images.githubusercontent.com/61604561/94182544-8ab67c80-fe77-11ea-9294-d28a85f3afb0.png)

mkmf.log only says: ""pkg-config --exists protobuf"
package configuration for protobuf is not found
"
I tried setting "c:\protobuf\protoc.exe" in the PATH at environment  variables.
The cmd was able to get the protoc --version:
![image](https://user-images.githubusercontent.com/61604561/94183074-3e1f7100-fe78-11ea-84cb-28b67921e2ed.png)

and the gcc --version:
![image](https://user-images.githubusercontent.com/61604561/94183021-2e079180-fe78-11ea-8c8e-d89b5e1bb9b5.png)

Can you help me solve it?

**Comment by akihikodaki** [comment]
It failed to find the library and header files, not the compiler. Install the files and check the installation with command `pkg-config --exists protobuf`.
