### ISSUE TITLE
warning: rb_safe_level will be removed in Ruby 3.0

### ISSUE THREAD

**Issue by shleeable** [akihikodaki/cld3-ruby#26]
cld3.rb:91: warning: rb_safe_level will be removed in Ruby 3.0 in `3.3.0`.

**Comment by akihikodaki** [comment]
I ran `rake spec && cd intermediate && bundle exec rspec -w` with 3.0.0 preview1 but was unable to reproduce the problem. I'll close this issue due to that but feel free to reopen it with a more concrete reproduction procedure.
