### ISSUE TITLE
FFI 1.15.0 support

### ISSUE THREAD

**Issue by ayanko** [akihikodaki/cld3-ruby#27]
Hi,

Some gems from my Gemfile requires `ffi >=1.15.0`.

Currently cld3 does not include this version:
```
gem.add_dependency "ffi", [ ">= 1.1.0", "< 1.15.0" ]
```

Is there anything that prevents us to enhance this gem to support 1.15.0?

https://github.com/ffi/ffi/blob/master/CHANGELOG.md#1150--2021-03-05

**Comment by akihikodaki** [comment]
Ruby-FFI 1.15.0 is now supported with commit fc3def8b867aa47e13231837adbdf4f22cbf292b, which has just been released as a part of 3.4.2.
