### ISSUE TITLE
ProtoBuf on GitHub CI

### ISSUE THREAD

**Issue by Adeynack** [akihikodaki/cld3-ruby#28]
Good day and let me first thank you for this GEM. It works perfectly for my needs!

I develop on macOS and there, using `brew install protobuf`, I was instantly able to work with the GEM.

However, I am using GitHub CI and there, `protobuf` is not installed by default. I tried a few ways of installing it on the CI, but nothing worked. It keeps failing to compile the native extensions of the GEM, stating that `protobuf` cannot be found.

It would help me to know which files and at which location it is expecting. Is it something that you could help me with?

Thanks in advance.

**Comment by akihikodaki** [comment]
See https://github.com/akihikodaki/cld3-ruby/blob/4dd40ead0d8d8b65f5379b4b739bf1b577d20228/.github/workflows/gempush.yml.
