### ISSUE TITLE
Please document how to install Protobuf dependency for Ubuntu

### ISSUE THREAD

**Issue by coezbek** [akihikodaki/cld3-ruby#31]
Could you add the following documentation under the `platform specific` section in the `readme`?

> On Ubuntu/Debian to install the necessary `protobuf` dependencies run:
> 
> ```
>   apt install libprotobuf-dev protobuf-compiler
> ```

**Comment by akihikodaki** [comment]
I'm sorry but it does not happen as described in https://github.com/akihikodaki/cld3-ruby/pull/29#issuecomment-879823675.
