### ISSUE TITLE
MAX_NUM_INPUT_BYTES_TO_CONSIDER isn't used

### ISSUE THREAD

**Issue by coezbek** [akihikodaki/cld3-ruby#33]
The documentation mentions the constant `MAX_NUM_INPUT_BYTES_TO_CONSIDER` as the maximum number of bytes which are processed for `find_top_n_most_freq_langs`, but it seems the variable isn't really used. 

Is this intentional just to show the constant as used by CLD3 or is there an issue that this constants isn't used to initialize a buffer?

**Comment by akihikodaki** [comment]
It is intentional.
