### ISSUE TITLE
Different results returned based on `MAX_NUM_BYTES_TO_CONSIDER`

### ISSUE THREAD

**Issue by coezbek** [akihikodaki/cld3-ruby#34]
I was investigating a chunk of text being wrongly labeled as `uk` (Ukranian), when it was `el` (Greek). It turned out that the misclassification just happens with certain values of `MAX_NUM_BYTES_TO_CONSIDER` and when using `find_language`. 

```ruby
# Kafka text as an example + the word Velcro
text = "Πολυαγαπημένε πατέρα πρόσφατα Velcro με ρώτησες κάποια φορά γιατί ισχυρίζομαι πως σε φοβάμαι. Εγώ δεν ήξερα, ως συνήθως, τι να σου απαντήσω, εν μέρει ακριβώς λόγω του φόβου που νιώθω για σένα, εν μέρει επειδή στην αιτιολόγηση του φόβου αυτού συγκαταλέγονται πάρα πολλές λεπτομέρειες, που εν τη ρύμη του λόγου εγώ ούτε κατά το ήμισυ δεν θα μπορούσα να τις συγκρατήσω. Κι αν εδώ προσπαθώ να σου απαντήσω γραπτώς, μόνο ανολοκλήρωτο κατά πολύ θα αποβεί και τούτο, επειδή και κατά τη γραφή ο φόβος και οι συνέπειές του με κωλύουν έναντί σου κι επειδή το μέγεθος του υλικού εν γένει υπερβαίνει κατά πολύ τη μνήμη μου και το λογικό μου. Για σένα το ζήτημα αποδεικνυόταν πάντοτε πολύ απλό, τουλάχιστον στον βαθμό που μιλούσες εσύ γι’ αυτό ενώπιόν μου και, αδιακρίτως, ενώπιον πολλών άλλων. Εσένα σου φαινόταν να είναι κάπως έτσι: Εσύ εργαζόσουν σκληρά σ’ όλη σου τη ζωή, τα πάντα για τα παιδιά σου, προ πάντων για εμένα τα θυσίαζες, εγώ έκαμνα συνεπώς «ζωή χαρισάμενη», είχα πλήρη ελευθερία να μάθω ό,τι ήθελα, κανέναν λόγο δεν είχα να έχω έγνοιες για την καθημερινή διατροφή, να έχω έγνοιες συνεπώς εν γένει• εσύ αντ’ αυτών καμμίαν ευγνωμοσύνη δεν αξίωνες, γνωρίζεις «την ευγνωμοσύνη των παιδιών, αλλά εν τούτοις τουλάχιστον μια "

200.times { |i|
  max_bytes = 500 + i * 10
  cld3 = CLD3::NNetLanguageIdentifier.new(180, max_bytes)

  lang = cld3.find_language(text)
  lang2 = cld3.find_top_n_most_freq_langs(text, 1)

  puts "When max_bytes is #{max_bytes} probability is less than 0.999: #{lang.probability}" if lang.probability < 0.999

  if lang.language != :el
    puts "When max_bytes is #{max_bytes} then cld3::find_language returns #{lang.language},
      find_top_n_most_freq_langs returns #{lang2.first.language}"
    #pp lang
    #pp lang2
  end
}

puts "Size: #{text.length} - Bytesize: #{text.encode(Encoding::UTF_8).bytesize}"
```

When I run this, I get a low probability detection for `max_bytes == 1660 to 1690`. 

If I vary the `MIN_BYTES_TO_CONSIDER` then ruby interpreter crashes with illegal instruction / access violations.

**Comment by akihikodaki** [comment]
That is a fault of the upstream project and I'm not going to fix that.

> If I vary the MIN_BYTES_TO_CONSIDER then ruby interpreter crashes with illegal instruction / access violations.

It should not crash whatever given and needs a fix. Please open another issue with the reproduction and your environment details, especially the precise version of the operating system and the distribution of Ruby and protobuf you use.

**Comment by coezbek** [comment]
> That is a fault of the upstream project and I'm not going to fix that.

Are you sure this is the case? I am happy to report this upstream, but wanted to make sure that it is not a memory issue in the wrapper code.

> Please open another issue with the reproduction and your environment details, especially the precise version of the operating system and the distribution of Ruby and protobuf you use.

Will do so.

**Comment by akihikodaki** [comment]
> > That is a fault of the upstream project and I'm not going to fix that.
> 
> Are you sure this is the case? I am happy to report this upstream, but wanted to make sure that it is not a memory issue in the wrapper code.

A quick search revealed this: https://github.com/akihikodaki/cld3-ruby/issues/17#issuecomment-381385609
So yes, it is unlikely that is an issue of the wrapper code.

> > Please open another issue with the reproduction and your environment details, especially the precise version of the operating system and the distribution of Ruby and protobuf you use.
>
> Will do so.

Thanks in advance.
